### ISSUE TITLE
Private mcchat causes issues (NPEs) with multiple plugins

### ISSUE THREAD

**Issue by NorbiPeti** [TBMCPlugins/DiscordPlugin#106]
Player join:
```
        at com.massivecraft.massivecore.event.EventMassiveCorePlayerUpdate.getMaxHealth(EventMassiveCorePlayerUpdate.java:126) ~[?:?]

        at org.dynmap.bukkit.DynmapPlugin$BukkitPlayer.getName(DynmapPlugin.java:597) ~[?:?] (Multiple times)
```

Player leave:
```
        at com.earth2me.essentials.EssentialsPlayerListener.onPlayerQuit(EssentialsPlayerListener.java:174) ~[?:?]
```

**Comment by NorbiPeti** [comment]
https://github.com/EssentialsX/Essentials/blob/deaeb46ce9ded5b8706c539961ea4b532218dd7f/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L174
